# encoding: utf8

class PylolException(Exception):
    '''Base class for all exceptions generated by PyLoL'''
    pass

class APIFailure(PylolException):
    '''Thrown when an API request returns success = false'''
    pass

class InvalidRegion(PylolException):
    '''Thrown when an invalid region is specified during an API query'''

    def __init__(self, region):
        self.message = u'%s is not a valid region.' % region
        self.region = region
